services:
  - type: web
    name: my-pwa-chat
    runtime: python
    plan: free
    rootDir: render
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: FIREBASE_BASE_URL
        value: https://chat-app-136b8-default-rtdb.firebaseio.com
      - key: FIREBASE_ROOT
        value: my_pwa_chat
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SECRET_KEY
        generateValue: true
